### ISSUE TITLE
Reproduction Difference

### ISSUE THREAD

**Issue by AhmadM-DL** [linusericsson/ssl-transfer#3]
Hello!

First, I want to acknowledge the effort you have done testing all those models on different datasets. Thanks for that.

I am trying to reproduce InfoMin model performance on the DTD dataset.
However, I am achieving a score that is below the reported score by 10 degrees of performance.

Any thoughts?

**Comment by AhmadM-DL** [comment]
I will try some more experiments and see if there is anything wrong in my configurations

**Comment by linusericsson** [comment]
Hi Ahmad,

Thanks for your interest and help in checking reproducibility!

I assume you're referring to the many-shot linear evaluation setting. I've rerun this myself just now:
`python linear.py -d dtd -m infomin -c 56.23413185099295`
and the accuracy I get is: 75.16%

And when doing the hyperparameter search:
`python linear.py -d dtd -m infomin`
I get 74.73% which is the value reported in our paper.

The difference between these two runs should be due to randomness.

**Comment by AhmadM-DL** [comment]
I see. I tried the model you provided and it results in the same.
Initially I was using the model provided by PyContrast repo.
It seems something went wrong with the loading process.
